

-- Table XXXTABLE

RENAME TABLE XXXTABLE TO XXXTABLE_old;

CREATE TABLE `XXXTABLE` (
  `XXXID` bigint(20) NOT NULL AUTO_INCREMENT,
  `XXXStatus` varchar(32) NOT NULL DEFAULT 'AprioriGood'
) ENGINE=InnoDB;

SET UNIQUE_CHECKS=0;
ALTER TABLE XXXTABLE DISABLE KEYS;
INSERT INTO XXXTABLE (XXXID,XXXStatus) SELECT XXXID,XXXStatus FROM XXXTABLE_old; 
ALTER TABLE XXXTABLE ENABLE KEYS;
SET UNIQUE_CHECKS=1;

DROP TABLE XXXTABLE_old;
